"""Emit T-SQL that seeds a Fabric Warehouse with the synthetic call corpus.

Fabric Warehouse has no bulk JSON loader, and the Lakehouse path goes through
Spark, which is easy to starve on an F2 capacity. Generating a plain T-SQL
script keeps seeding independent of Spark and lets the customer paste it into
the Warehouse query editor, run it through sqlcmd, or check it into a release
pipeline.

Usage:
    python data/load_corpus_to_warehouse.py > seed_warehouse.sql
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

DEFAULT_CORPUS = Path(__file__).parent / "synthetic-call-corpus" / "call_analytics.jsonl"

# Column order is fixed so the generated INSERT is positional and stable.
COLUMNS: tuple[tuple[str, str], ...] = (
    ("call_id", "VARCHAR(100) NOT NULL"),
    ("call_start_utc", "DATETIME2(6) NOT NULL"),
    ("queue_name", "VARCHAR(100) NOT NULL"),
    ("region", "VARCHAR(50) NOT NULL"),
    ("customer_intent", "VARCHAR(100) NOT NULL"),
    ("disposition", "VARCHAR(100) NOT NULL"),
    ("pii_safe_summary", "VARCHAR(4000) NOT NULL"),
    ("sentiment", "VARCHAR(50) NOT NULL"),
    ("escalation_flag", "BIT NOT NULL"),
    ("cancellation_flag", "BIT NOT NULL"),
    ("competitor", "VARCHAR(100) NULL"),
    ("competitor_mentions", "INT NOT NULL"),
    ("handle_time_seconds", "INT NULL"),
    ("repeat_contact_flag", "BIT NULL"),
    ("account_tenure_months", "INT NULL"),
    ("monthly_revenue_usd", "DECIMAL(12,2) NULL"),
    ("ingestion_utc", "DATETIME2(6) NOT NULL"),
)

# T-SQL caps a single INSERT ... VALUES at 1000 row constructors.
ROWS_PER_INSERT = 500


def _literal(column: str, value: Any) -> str:
    if value is None:
        return "NULL"
    if column.endswith("_utc"):
        # Trim the trailing Z; DATETIME2 has no offset component.
        return "'" + str(value).rstrip("Z").replace("'", "''") + "'"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def build_script(rows: list[dict[str, Any]], schema: str, table: str) -> str:
    qualified = f"{schema}.{table}"
    column_names = ", ".join(name for name, _ in COLUMNS)
    definitions = ",\n  ".join(f"{name} {sql_type}" for name, sql_type in COLUMNS)

    parts: list[str] = [
        f"-- Seed {qualified} with {len(rows)} synthetic PII-safe call records.",
        "-- Generated by data/load_corpus_to_warehouse.py; do not edit by hand.",
        "",
        f"IF OBJECT_ID('{qualified}', 'U') IS NOT NULL DROP TABLE {qualified};",
        "GO",
        "",
        f"CREATE TABLE {qualified} (\n  {definitions}\n);",
        # GO is required, not cosmetic. Without a batch separator the INSERT is
        # compiled against the table metadata as it existed before CREATE TABLE,
        # so re-seeding a table whose shape changed fails with
        # "Invalid column name" on every new column.
        "GO",
        "",
    ]

    for start in range(0, len(rows), ROWS_PER_INSERT):
        chunk = rows[start : start + ROWS_PER_INSERT]
        tuples = ",\n".join(
            "  (" + ", ".join(_literal(name, row.get(name)) for name, _ in COLUMNS) + ")"
            for row in chunk
        )
        parts.append(f"INSERT INTO {qualified} ({column_names}) VALUES\n{tuples};")
        parts.append("GO")
        parts.append("")

    parts.append(f"SELECT COUNT(*) AS seeded_rows FROM {qualified};")
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS)
    parser.add_argument("--schema", default="dbo")
    parser.add_argument("--table", default="call_analytics")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    if not args.corpus.exists():
        raise SystemExit(
            f"Corpus not found at {args.corpus}. Run generate_synthetic_call_corpus.py first."
        )

    with args.corpus.open(encoding="utf-8") as handle:
        rows = [json.loads(line) for line in handle if line.strip()]

    script = build_script(rows, args.schema, args.table)
    if args.output:
        args.output.write_text(script + "\n", encoding="utf-8", newline="\n")
        print(f"Wrote {args.output} ({len(rows)} rows).", file=sys.stderr)
    else:
        sys.stdout.write(script + "\n")


if __name__ == "__main__":
    main()
