"""
Speech-to-text accuracy + latency benchmark for the three architectures.

Runs `data/mock-call.wav` (generated by `tts.py`) through three STT pipelines and
scores each against the original `mock-call-transcript.txt`:

  1. Azure Speech real-time  - classic `azure-cognitiveservices-speech` SDK
     (`SpeechRecognizer`, continuous recognition). Truly incremental: the service
     runs its own VAD and finalizes each utterance as audio streams in.
  2. MAI-Transcribe-1.5 real-time - Voice Live WebSocket, with
     `input_audio_transcription.model = "mai-transcribe"`.
  3. MAI-Transcribe-1.5 batch - the whole call in a single fast-transcription REST
     call. Not usable mid-call, but it is the cheapest and lowest-effort option when
     summarization and redaction happen after the call ends.

Fair segmentation
-----------------
MAI-Transcribe has no incremental streaming path: it never emits
`input_audio_transcription.delta`, and Voice Live's own VAD returns a transcript only
for the first turn of a session (verified against server VAD, semantic VAD,
`create_response`, and manual `response.create`). It must therefore be driven with
explicit buffer commits.

Committing on a fixed clock would slice utterances mid-sentence and punish MAI for
our chunking rather than its recognition (at a 3s cadence WER nearly quadruples).
Instead we run a local VAD over the audio and commit at natural pauses - the same
kind of boundary the Speech SDK picks internally - so both real-time engines see
equivalent segments.

Latency
-------
For all engines latency is *finalization lag*: the delay between the end of an
utterance's audio and the arrival of its final transcript. That is measured the same
way on both real-time paths, so the numbers are directly comparable. Architecture 3
is reported as whole-call turnaround instead, since it has no per-utterance notion.

Note that MAI still pays a structural penalty in real time: it cannot return anything
until an utterance closes, whereas the Speech SDK streams partial hypotheses while the
speaker is still talking.

All three architectures run concurrently, so a full pass costs roughly one call
duration rather than three.

Authentication uses Microsoft Entra ID (`DefaultAzureCredential`) because local
(key-based) auth is disabled on the Speech resource.
"""

import array
import asyncio
import base64
import json
import math
import re
import statistics
import string
import time
import wave
from pathlib import Path

import azure.cognitiveservices.speech as speechsdk
import jiwer
import requests
import websockets
from azure.identity import DefaultAzureCredential

RESOURCE_NAME = "charter-stt-pii-resource"
SPEECH_ENDPOINT = f"https://{RESOURCE_NAME}.cognitiveservices.azure.com"
RESOURCE_ID = (
    "/subscriptions/fd918039-a89e-49a7-8e32-af614b3765f9"
    "/resourceGroups/rg-charter-stt-pii"
    f"/providers/Microsoft.CognitiveServices/accounts/{RESOURCE_NAME}"
)

VOICE_LIVE_URL = (
    f"wss://{RESOURCE_NAME}.services.ai.azure.com/voice-live/realtime"
    "?api-version=2026-04-10&model=gpt-4.1"
)
FAST_TRANSCRIPTION_API_VERSION = "2025-10-15"

CHUNK_SECONDS = 0.1  # audio is streamed to Voice Live in 100 ms frames

# Local VAD, tuned against this call: 103 segments, median 2.6s, which is the same
# ballpark as the 73 utterances the Speech SDK finds on its own.
VAD_FRAME_SECONDS = 0.02
VAD_RMS_THRESHOLD = 150
VAD_MIN_SILENCE_SECONDS = 0.5
VAD_MAX_UTTERANCE_SECONDS = 20.0

DATA_DIR = Path(__file__).parent
AUDIO_PATH = DATA_DIR / "mock-call.wav"
TRANSCRIPT_PATH = DATA_DIR / "mock-call-transcript.txt"
RESULTS_PATH = DATA_DIR / "stt-benchmark-results.json"

SPEAKER_RE = re.compile(r"^(REP|CUSTOMER):\s*(.*)$")
# Uploaded transcripts use their own speaker labels ("Agent:", "Caller 2:"), which
# are formatting rather than spoken words and must not be scored.
GENERIC_SPEAKER_RE = re.compile(r"^([A-Za-z][\w'-]*(?:[ ][\w'-]+){0,2}):\s+(.*)$")
DIRECTION_RE = re.compile(r"\[[^\]]*\]")

# Spoken-form expansions so scoring compares words, not formatting choices.
NORMALIZATIONS = [
    (r"\bmr\b", "mister"),
    (r"\bms\b", "miss"),
    (r"\bmrs\b", "missus"),
    (r"\bdr\b", "doctor"),
    (r"\bok\b", "okay"),
    (r"\bwi fi\b", "wifi"),
    (r"\bwi-fi\b", "wifi"),
    (r"\be[- ]mail\b", "email"),
    (r"\bam\b", "a m"),
    (r"\bpm\b", "p m"),
    (r"\$(\d+)", r"\1 dollars"),
    (r"%", " percent"),
]

# The engines apply different inverse text normalization ("three hundred" vs "300",
# "eleventh" vs "11th", "4111 1111" vs "4111111"). Numbers are folded into a single
# canonical digit form on both sides so WER reflects recognition quality rather than
# formatting style.
UNITS = {
    "zero": 0, "oh": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10, "eleven": 11,
    "twelve": 12, "thirteen": 13, "fourteen": 14, "fifteen": 15, "sixteen": 16,
    "seventeen": 17, "eighteen": 18, "nineteen": 19,
}
TENS = {
    "twenty": 20, "thirty": 30, "forty": 40, "fifty": 50,
    "sixty": 60, "seventy": 70, "eighty": 80, "ninety": 90,
}
ORDINALS = {
    "first": "one", "second": "two", "third": "three", "fourth": "four",
    "fifth": "five", "sixth": "six", "seventh": "seven", "eighth": "eight",
    "ninth": "nine", "tenth": "ten", "eleventh": "eleven", "twelfth": "twelve",
    "thirteenth": "thirteen", "fourteenth": "fourteen", "fifteenth": "fifteen",
    "sixteenth": "sixteen", "seventeenth": "seventeen", "eighteenth": "eighteen",
    "nineteenth": "nineteen", "twentieth": "twenty", "thirtieth": "thirty",
}


# --------------------------------------------------------------------------- #
# Reference transcript + scoring
# --------------------------------------------------------------------------- #
def reference_text(path: Path = TRANSCRIPT_PATH) -> str:
    """Reference = exactly the words that were fed to TTS, in order.

    The mock call is speaker-labelled (`REP:` / `CUSTOMER:`), and so are most real
    call transcripts. When any speaker labels are present only labelled lines are
    scored, so headers and section markers stay out of the reference. A transcript
    with no labels at all is taken as plain prose instead.
    """
    lines = [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    labelled = [
        match
        for match in (SPEAKER_RE.match(line) or GENERIC_SPEAKER_RE.match(line)
                      for line in lines)
        if match
    ]

    if labelled:
        spoken = [match.group(2) for match in labelled]
    else:
        spoken = lines

    return " ".join(DIRECTION_RE.sub(" ", text) for text in spoken)


def words_to_digits(tokens: list[str]) -> list[str]:
    """Convert spoken number words into digit tokens (e.g. 'eighty two' -> '82')."""
    out: list[str] = []
    index = 0
    while index < len(tokens):
        token = ORDINALS.get(tokens[index], tokens[index])
        if token not in UNITS and token not in TENS:
            out.append(tokens[index])
            index += 1
            continue

        value = TENS[token] if token in TENS else UNITS[token]
        index += 1
        if token in TENS and index < len(tokens):
            nxt = ORDINALS.get(tokens[index], tokens[index])
            if nxt in UNITS and UNITS[nxt] < 10:
                value += UNITS[nxt]
                index += 1
        while index < len(tokens) and tokens[index] in ("hundred", "thousand"):
            value *= 100 if tokens[index] == "hundred" else 1000
            index += 1
        out.append(str(value))
    return out


def fold_numbers(text: str) -> str:
    """Digitize number words, drop ordinal suffixes, and join adjacent digit runs."""
    tokens = words_to_digits(text.split())
    tokens = [re.sub(r"^(\d+)(st|nd|rd|th)$", r"\1", t) for t in tokens]

    folded: list[str] = []
    for token in tokens:
        if token.isdigit() and folded and folded[-1].isdigit():
            folded[-1] += token
        else:
            folded.append(token)
    return " ".join(folded)


def normalize(text: str) -> str:
    """Lowercase, expand abbreviations, drop punctuation, canonicalize numbers."""
    text = text.lower().replace("\n", " ")
    text = re.sub(r"(?<=\d),(?=\d)", "", text)  # 1,000 -> 1000
    for pattern, replacement in NORMALIZATIONS:
        text = re.sub(pattern, replacement, text)
    text = text.translate(str.maketrans({c: " " for c in string.punctuation}))
    text = re.sub(r"\s+", " ", text).strip()
    return fold_numbers(text)


def score(reference: str, hypothesis: str) -> dict:
    measures = jiwer.process_words(normalize(reference), normalize(hypothesis))
    return {
        "wer": measures.wer,
        "accuracy": 1.0 - measures.wer,
        "substitutions": measures.substitutions,
        "deletions": measures.deletions,
        "insertions": measures.insertions,
        "hits": measures.hits,
    }


def lag_stats(lags: list[float]) -> dict:
    """Finalization lag = delay from end of an utterance's audio to its transcript."""
    if not lags:
        return {"mean": None, "median": None, "p95": None, "max": None, "count": 0}
    ordered = sorted(lags)
    return {
        "mean": statistics.fmean(lags),
        "median": statistics.median(lags),
        "p95": ordered[min(len(ordered) - 1, int(0.95 * len(ordered)))],
        "max": ordered[-1],
        "count": len(lags),
    }


def get_token() -> str:
    credential = DefaultAzureCredential()
    return credential.get_token("https://cognitiveservices.azure.com/.default").token


def load_audio(path: Path = AUDIO_PATH) -> tuple[bytes, int]:
    with wave.open(str(path)) as wav:
        if wav.getnchannels() != 1 or wav.getsampwidth() != 2:
            raise ValueError(
                f"{path.name}: expected 16-bit mono PCM WAV, got "
                f"{wav.getnchannels()} channel(s) / {wav.getsampwidth() * 8}-bit"
            )
        return wav.readframes(wav.getnframes()), wav.getframerate()


# --------------------------------------------------------------------------- #
# Local VAD - shared utterance boundaries
# --------------------------------------------------------------------------- #
def find_utterances(pcm: bytes, sample_rate: int) -> list[tuple[float, float]]:
    """Return [(start_seconds, end_seconds), ...] for speech separated by pauses.

    Commits are aligned to these boundaries so MAI is chunked the way the Speech
    SDK's own endpointing would chunk it, instead of on an arbitrary clock.
    """
    samples = array.array("h")
    samples.frombytes(pcm)
    frame = int(sample_rate * VAD_FRAME_SECONDS)

    utterances: list[tuple[float, float]] = []
    start_frame: int | None = None
    silent_run = 0
    min_silent_frames = int(VAD_MIN_SILENCE_SECONDS / VAD_FRAME_SECONDS)

    for index in range(len(samples) // frame):
        window = samples[index * frame : (index + 1) * frame]
        rms = math.sqrt(sum(s * s for s in window) / frame)

        if rms > VAD_RMS_THRESHOLD:
            if start_frame is None:
                start_frame = index
            silent_run = 0
            # Force a boundary so one long monologue cannot stall the stream.
            if (index - start_frame) * VAD_FRAME_SECONDS >= VAD_MAX_UTTERANCE_SECONDS:
                utterances.append(
                    (start_frame * VAD_FRAME_SECONDS, index * VAD_FRAME_SECONDS)
                )
                start_frame = None
        elif start_frame is not None:
            silent_run += 1
            if silent_run >= min_silent_frames:
                end = (index - silent_run) * VAD_FRAME_SECONDS
                utterances.append((start_frame * VAD_FRAME_SECONDS, end))
                start_frame = None
                silent_run = 0

    if start_frame is not None:
        total = (len(samples) // frame) * VAD_FRAME_SECONDS
        utterances.append((start_frame * VAD_FRAME_SECONDS, total))
    return utterances


# --------------------------------------------------------------------------- #
# Architecture 1 - Azure Speech real-time (Speech SDK continuous recognition)
# --------------------------------------------------------------------------- #
class ThrottledPcmStream(speechsdk.audio.PullAudioInputStreamCallback):
    """Feeds PCM to the Speech SDK at 1x.

    A file-based `AudioConfig` lets the SDK consume audio as fast as it can (~2x
    here), which makes streaming latency meaningless. Pacing the pull stream to
    wall-clock time reproduces a real-time call.
    """

    def __init__(self, pcm: bytes, bytes_per_second: int) -> None:
        super().__init__()
        self._pcm = pcm
        self._bytes_per_second = bytes_per_second
        self._position = 0
        self._start: float | None = None

    def read(self, buffer: memoryview) -> int:
        if self._start is None:
            self._start = time.perf_counter()
        size = min(len(buffer), len(self._pcm) - self._position)
        if size <= 0:
            return 0

        end = self._position + size
        delay = (self._start + end / self._bytes_per_second) - time.perf_counter()
        if delay > 0:
            time.sleep(delay)

        buffer[:size] = self._pcm[self._position : end]
        self._position = end
        return size

    def close(self) -> None:
        return None


def run_azure_speech_realtime(token: str, pcm: bytes, sample_rate: int) -> tuple:
    speech_config = speechsdk.SpeechConfig(endpoint=SPEECH_ENDPOINT)
    speech_config.authorization_token = f"aad#{RESOURCE_ID}#{token}"
    speech_config.speech_recognition_language = "en-US"

    stream_format = speechsdk.audio.AudioStreamFormat(
        samples_per_second=sample_rate, bits_per_sample=16, channels=1
    )
    callback = ThrottledPcmStream(pcm, sample_rate * 2)
    pull_stream = speechsdk.audio.PullAudioInputStream(callback, stream_format)
    audio_config = speechsdk.audio.AudioConfig(stream=pull_stream)
    recognizer = speechsdk.SpeechRecognizer(
        speech_config=speech_config, audio_config=audio_config
    )

    phrases: list[str] = []
    lags: list[float] = []
    finished: list[bool] = []
    start = time.perf_counter()

    def on_recognized(evt: speechsdk.SpeechRecognitionEventArgs) -> None:
        if evt.result.reason != speechsdk.ResultReason.RecognizedSpeech:
            return
        if not evt.result.text:
            return
        phrases.append(evt.result.text)
        # offset/duration are in 100-nanosecond ticks from the start of the stream,
        # so this is the lag from the end of the utterance's audio.
        audio_end = (evt.result.offset + evt.result.duration) / 1e7
        lags.append(max(0.0, (time.perf_counter() - start) - audio_end))

    def on_canceled(evt: speechsdk.SpeechRecognitionCanceledEventArgs) -> None:
        if evt.reason == speechsdk.CancellationReason.Error:
            print(f"  ! Speech SDK canceled: {evt.error_details}")
        finished.append(True)

    recognizer.recognized.connect(on_recognized)
    recognizer.canceled.connect(on_canceled)
    recognizer.session_stopped.connect(lambda _: finished.append(True))

    recognizer.start_continuous_recognition()
    while not finished:
        time.sleep(0.2)
    recognizer.stop_continuous_recognition()

    wall = time.perf_counter() - start
    metrics = {
        "mode": "real-time (incremental)",
        "wall_seconds": wall,
        # Transcription overlaps the call, so the transcript is done moments after
        # the caller stops talking.
        "time_to_full_transcript": wall,
        "finalization_lag": lag_stats(lags),
        "segments": len(phrases),
    }
    return " ".join(phrases), metrics


# --------------------------------------------------------------------------- #
# Architecture 2 - MAI-Transcribe-1.5 real-time (Voice Live, VAD-aligned commits)
# --------------------------------------------------------------------------- #
async def run_mai_realtime(token: str, pcm: bytes, sample_rate: int) -> tuple:
    bytes_per_second = sample_rate * 2
    chunk_bytes = int(bytes_per_second * CHUNK_SECONDS)
    utterances = find_utterances(pcm, sample_rate)
    commit_at = [end for _, end in utterances]

    transcripts: list[str] = []
    lags: list[float] = []
    pending: list[float] = []  # wall-clock time each utterance's audio finished
    start = time.perf_counter()

    async with websockets.connect(
        VOICE_LIVE_URL,
        additional_headers={"Authorization": f"Bearer {token}"},
        max_size=None,
        ping_interval=20,
        ping_timeout=60,
    ) as socket:
        await socket.recv()  # session.created
        await socket.send(
            json.dumps(
                {
                    "type": "session.update",
                    "session": {
                        "modalities": ["text"],
                        "input_audio_format": "pcm16",
                        "input_audio_transcription": {"model": "mai-transcribe"},
                        "turn_detection": None,
                    },
                }
            )
        )

        async def reader() -> None:
            async for raw in socket:
                event = json.loads(raw)
                if event["type"] == "error":
                    message = event["error"].get("message", "")
                    if "buffer too small" not in message:
                        print(f"  ! Voice Live: {message}")
                elif event["type"].endswith("input_audio_transcription.completed"):
                    if pending:
                        lags.append(max(0.0, time.perf_counter() - pending.pop(0)))
                    if event.get("transcript"):
                        transcripts.append(event["transcript"])

        reader_task = asyncio.create_task(reader())

        # Stream at 1x, committing when each utterance's audio has been sent.
        next_commit = 0
        next_send = start
        for offset in range(0, len(pcm), chunk_bytes):
            chunk = pcm[offset : offset + chunk_bytes]
            await socket.send(
                json.dumps(
                    {
                        "type": "input_audio_buffer.append",
                        "audio": base64.b64encode(chunk).decode(),
                    }
                )
            )

            sent_seconds = (offset + len(chunk)) / bytes_per_second
            if next_commit < len(commit_at) and sent_seconds >= commit_at[next_commit]:
                await socket.send(json.dumps({"type": "input_audio_buffer.commit"}))
                pending.append(time.perf_counter())
                next_commit += 1

            next_send += CHUNK_SECONDS
            await asyncio.sleep(max(0.0, next_send - time.perf_counter()))

        deadline = time.perf_counter() + 60
        while pending and time.perf_counter() < deadline:
            await asyncio.sleep(0.2)
        reader_task.cancel()

    wall = time.perf_counter() - start
    metrics = {
        "mode": "real-time (utterance micro-batch)",
        "wall_seconds": wall,
        "time_to_full_transcript": wall,
        "finalization_lag": lag_stats(lags),
        "segments": len(transcripts),
        "utterances_committed": len(commit_at),
    }
    return " ".join(transcripts), metrics


# --------------------------------------------------------------------------- #
# Architecture 3 - MAI-Transcribe-1.5 batch (whole call in one REST call)
# --------------------------------------------------------------------------- #
def run_mai_batch(
    token: str, audio_path: Path = AUDIO_PATH, audio_seconds: float = 0.0
) -> tuple:
    url = (
        f"{SPEECH_ENDPOINT}/speechtotext/transcriptions:transcribe"
        f"?api-version={FAST_TRANSCRIPTION_API_VERSION}"
    )
    definition = {
        "locales": ["en"],
        "enhancedMode": {
            "enabled": True,
            "model": "mai-transcribe-1.5",
            "transcribeStyle": "verbatim",
        },
    }

    with audio_path.open("rb") as audio:
        files = {
            "audio": (audio_path.name, audio, "audio/wav"),
            "definition": (None, json.dumps(definition), "application/json"),
        }
        start = time.perf_counter()
        response = requests.post(
            url, headers={"Authorization": f"Bearer {token}"}, files=files, timeout=900
        )
        latency = time.perf_counter() - start

    response.raise_for_status()
    payload = response.json()
    text = " ".join(p["text"] for p in payload.get("combinedPhrases", []))

    metrics = {
        "mode": "batch (post-call)",
        "wall_seconds": latency,
        "turnaround_seconds": latency,
        # Batch cannot start until the caller hangs up, so from the moment the call
        # begins the transcript is only ready after the full call plus turnaround.
        "time_to_full_transcript": audio_seconds + latency,
        "finalization_lag": lag_stats([]),
        "segments": len(payload.get("combinedPhrases", [])),
    }
    return text, metrics


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #
ENGINES = {
    "architecture-1-azure-speech-realtime": "1. Azure Speech real-time (SDK)",
    "architecture-2-mai-transcribe-realtime": (
        "2. MAI-Transcribe-1.5 real-time (Voice Live)"
    ),
    "architecture-3-mai-transcribe-batch": "3. MAI-Transcribe-1.5 batch (one call)",
}


async def _run_all(
    token: str,
    pcm: bytes,
    sample_rate: int,
    audio_path: Path = AUDIO_PATH,
    audio_seconds: float = 0.0,
    on_progress=None,
) -> dict:
    """Run all three architectures concurrently - they are independent sessions."""
    loop = asyncio.get_running_loop()

    async def tracked(key, awaitable):
        if on_progress:
            on_progress(key, "running")
        try:
            result = await awaitable
        except Exception as error:  # one engine failing must not sink the others
            if on_progress:
                on_progress(key, "failed")
            return error
        if on_progress:
            on_progress(key, "done")
        return result

    keys = list(ENGINES)
    speech, mai_realtime, mai_batch = await asyncio.gather(
        tracked(
            keys[0],
            loop.run_in_executor(
                None, run_azure_speech_realtime, token, pcm, sample_rate
            ),
        ),
        tracked(keys[1], run_mai_realtime(token, pcm, sample_rate)),
        tracked(
            keys[2],
            loop.run_in_executor(
                None, run_mai_batch, token, audio_path, audio_seconds
            ),
        ),
    )
    outcomes = [speech, mai_realtime, mai_batch]
    return {key: (ENGINES[key], outcome) for key, outcome in zip(keys, outcomes)}


def run_benchmark(
    audio_path: Path = AUDIO_PATH,
    reference_path: Path | None = TRANSCRIPT_PATH,
    on_progress=None,
) -> dict:
    """Benchmark all three architectures against `audio_path`.

    `reference_path` is optional: without it the transcripts and latency metrics are
    still produced, but there is no reference to score word error rate against.
    """
    reference = reference_text(reference_path) if reference_path else None
    pcm, sample_rate = load_audio(audio_path)
    audio_seconds = len(pcm) / (sample_rate * 2)
    utterances = find_utterances(pcm, sample_rate)

    token = get_token()
    runs = asyncio.run(
        _run_all(token, pcm, sample_rate, audio_path, audio_seconds, on_progress)
    )

    results = {}
    for key, (label, outcome) in runs.items():
        if isinstance(outcome, Exception):
            results[key] = {"label": label, "error": str(outcome), "transcript": ""}
            continue
        hypothesis, metrics = outcome
        if reference is not None:
            metrics.update(score(reference, hypothesis))
        metrics["word_count"] = len(normalize(hypothesis).split())
        results[key] = {"label": label, "metrics": metrics, "transcript": hypothesis}

    return {
        "audio_seconds": audio_seconds,
        "vad_utterances": len(utterances),
        "reference_words": (
            len(normalize(reference).split()) if reference is not None else None
        ),
        "scored": reference is not None,
        "engines": results,
    }


def main() -> None:
    pcm, sample_rate = load_audio()
    audio_seconds = len(pcm) / (sample_rate * 2)

    print(f"Audio:      {AUDIO_PATH.name} ({audio_seconds:.1f}s)")
    print(
        f"Running all 3 architectures concurrently "
        f"(~{audio_seconds / 60:.0f} min, bounded by 1x streaming)...\n"
    )

    report = run_benchmark(AUDIO_PATH, TRANSCRIPT_PATH)
    results = report["engines"]

    print(f"Reference:  {report['reference_words']} words")
    print(f"Local VAD:  {report['vad_utterances']} utterances (shared boundaries)\n")

    for key, entry in results.items():
        transcript = entry.get("transcript", "")
        if transcript:
            (DATA_DIR / f"transcript-{key}.txt").write_text(
                transcript, encoding="utf-8"
            )

    header = (
        f"{'Architecture':<46}{'WER':>8}{'Accuracy':>10}"
        f"{'Mean lag':>10}{'p95 lag':>9}{'Transcript ready':>18}"
    )
    print(header)
    print("-" * len(header))
    for entry in results.values():
        if "error" in entry:
            print(f"{entry['label']:<46}{'failed: ' + entry['error']:>47}")
            continue
        m = entry["metrics"]
        lag = m["finalization_lag"]
        if lag["mean"] is None:
            latency = f"{m['turnaround_seconds']:>9.1f}s{'batch':>9}"
        else:
            latency = f"{lag['mean']:>9.2f}s{lag['p95']:>8.2f}s"
        print(
            f"{entry['label']:<46}{m['wer']:>7.2%}{m['accuracy']:>10.2%}"
            f"{latency}{m['time_to_full_transcript']:>17.1f}s"
        )
    print(
        "\n'Transcript ready' = seconds from the start of the call until the full "
        "transcript exists.\nReal-time overlaps the call; batch cannot start until "
        "the caller hangs up."
    )

    print()
    for entry in results.values():
        if "error" in entry:
            continue
        m = entry["metrics"]
        print(
            f"{entry['label']}: {m['mode']}, {m['substitutions']} sub / "
            f"{m['deletions']} del / {m['insertions']} ins"
        )

    # The transcripts are written alongside as `transcript-<architecture>.txt`.
    persisted = {
        key: {k: v for k, v in entry.items() if k != "transcript"}
        for key, entry in results.items()
    }
    RESULTS_PATH.write_text(
        json.dumps({**report, "engines": persisted}, indent=2),
        encoding="utf-8",
    )
    print(f"\nWrote {RESULTS_PATH}")


if __name__ == "__main__":
    main()
