CREATE TABLE CALL_ANALYTICS (
  CALL_ID VARCHAR2(100) PRIMARY KEY,
  CALL_START_UTC TIMESTAMP WITH TIME ZONE NOT NULL,
  QUEUE_NAME VARCHAR2(100) NOT NULL,
  REGION VARCHAR2(50) NOT NULL,
  CUSTOMER_INTENT VARCHAR2(100) NOT NULL,
  DISPOSITION VARCHAR2(100) NOT NULL,
  PII_SAFE_SUMMARY CLOB NOT NULL,
  SENTIMENT VARCHAR2(50) NOT NULL,
  ESCALATION_FLAG NUMBER(1) NOT NULL CHECK (ESCALATION_FLAG IN (0, 1)),
  CANCELLATION_FLAG NUMBER(1) NOT NULL CHECK (CANCELLATION_FLAG IN (0, 1)),
  COMPETITOR VARCHAR2(100),
  COMPETITOR_MENTIONS NUMBER(10) NOT NULL CHECK (COMPETITOR_MENTIONS >= 0),
  INGESTION_UTC TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX CALL_ANALYTICS_START_IX ON CALL_ANALYTICS (CALL_START_UTC);
CREATE INDEX CALL_ANALYTICS_COMPETITOR_IX ON CALL_ANALYTICS (COMPETITOR);
